### ISSUE TITLE
clap-3.0.0-beta.2 does not work on rustc below 1.54.0

### ISSUE THREAD

**Issue by kayshinonome** [gbdev/rgbobj#3]
```
kayshinonome@latitude-e6430 ~/Code/rgbobj $ cargo b
   Compiling clap v3.0.0-beta.2
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /home/kayshinonome/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.2/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap`

To learn more, run the command again with --verbose.
kayshinonome@latitude-e6430 ~/Code/rgbobj $
```
